### ISSUE TITLE
Terminal Bell Focuses Terminal Window

### ISSUE THREAD

**Issue by fmlatghor** [arcticicestudio/nord-alacritty#16]
So I found that this theme does this to me. I have two questions:
- Is this supposed to happen?
- How do I get rid of it?
--

OS: Fedora 33
Shell: ZSH
Alacritty: 0.8.0-dev

**Comment by arcticicestudio** [comment]
Hi @fmlatghor :wave:

This theme only defines colors but no code at all. It makes use of the theming API provided by Alacritty to create themes via YAML definitions. The described behavior sounds like this is either a bug in Alacritty, but more like this is a desired effect that [could be customized via configurations][c].

[c]: https://github.com/alacritty/alacritty/blob/17923efc/alacritty.yml#L315-L354

**Comment by fmlatghor** [comment]
> Hi @fmlatghor wave
> 
> This theme only defines colors but no code at all. It makes use of the theming API provided by Alacritty to create themes via YAML definitions. The described behavior sounds like this is either a bug in Alacritty, but more like this is a desired effect that [could be customized via configurations](https://github.com/alacritty/alacritty/blob/17923efc/alacritty.yml#L315-L354).

This happens exactly when I use this theme and only this theme, I don't really know what to tell you.

**Comment by fmlatghor** [comment]
I could try again to see if it happens, but eh, it might not change anything.

**Comment by arcticicestudio** [comment]
Are you sure that it actually really requests the OS to set the active window to Alacritty or is it just the visual perception?
It might be that you think that it takes focus, but in fact it simply uses the [`dim` colors defined by the theme][dc], including the [dimmed `foreground`][dcf] color. As soon as the terminal window actually gets the focus again, or any process sends a signal to the terminal that implies a activation, the normal colors are rendered by Alacritty.

The `dim` color were introduced in #12 with a [preview of the visual style added as comment][c].

Could you please post some details about your system, like the OS, to make it easier to identify the problem.

<p align="center"><strong>Normal</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/91131988-5b142900-e6ad-11ea-9ee0-b4f3196bb476.png" width="600" /></p>

<p align="center"><strong>Dimmed</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/91131970-59e2fc00-e6ad-11ea-9bbb-5631e012b6d8.png" width="600" /></p>

[dc]: https://github.com/arcticicestudio/nord-alacritty/blob/940c88a6/src/nord.yml#L50-L58
[dcf]: https://github.com/arcticicestudio/nord-alacritty/blob/940c88a6/src/nord.yml#L15
[c]: https://github.com/arcticicestudio/nord-alacritty/pull/12#issuecomment-679831345

**Comment by fmlatghor** [comment]
> Are you sure that it actually really requests the OS to set the active window to Alacritty or is it just the visual perception?
> It might be that you think that it takes focus, but in fact it simply uses the [`dim` colors defined by the theme](https://github.com/arcticicestudio/nord-alacritty/blob/940c88a6/src/nord.yml#L50-L58), including the [dimmed `foreground`](https://github.com/arcticicestudio/nord-alacritty/blob/940c88a6/src/nord.yml#L15) color. As soon as the terminal window actually gets the focus again, or any process sends a signal to the terminal that implies a activation, the normal colors are rendered by Alacritty.
> 
> The `dim` color were introduced in #12 with a [preview of the visual style added as comment](https://github.com/arcticicestudio/nord-alacritty/pull/12#issuecomment-679831345).
> 
> **Normal**
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/7836623/91131988-5b142900-e6ad-11ea-9ee0-b4f3196bb476.png">
> 
> **Dimmed**
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/7836623/91131970-59e2fc00-e6ad-11ea-9bbb-5631e012b6d8.png">
> 
> Could you also please post some details about your system, like the OS, to make it easier to identify the problem.

No it does, when I run `sleep 3 | tput bel`, the window pops up if I click on something else.

**Comment by arcticicestudio** [comment]
Could you please post some details about your setup, like the OS you run, your shell and Alacritty version.
Also, if possible, a screen record would be nice to get a better inside into what the problem looks like. You can simply attach the video to a comment in this issue since GitHub [finally shipped video upload and inline rendering support][gh-b-video_support] some weeks ago.

I've tried to reproduce the behavior, using `sleep 3 | tput bel` as trigger command, but it works fine in multiple scenarios.
I use the currently latest Alacritty version `0.7.2` and switched to [multiple color schemes from Alacritty's wiki][alacritty-wiki-cs], but none of them ever hijacked the OS window focus.

- With _ZSH_ and _Bash_ on Arch Linux using…
  - [GNOME][] as desktop environment with the default [Mutter][] rendering engine.
  - [sway][] as rendering engine and window manager.
  - [awesomeWM][] as window manager.
- With _ZSH_ and _Bash_ on macOS using…
  - the native rendering engine.
  - [Rectangle][] as window manager.
  - [yabai][] as window manager.

To be true, I've no more idea other than referring to search again through the issues in the Alacritty repository and open a new one if it has not been reported yet and if you can reproduce the problem in a stable way.

[alacritty-wiki-cs]: https://github.com/alacritty/alacritty/wiki/Color-schemes
[awesomewm]: https://github.com/awesomeWM/awesome
[gh-b-video_support]: https://github.blog/changelog/2021-02-01-expanded-support-for-video-uploads
[gnome]: https://www.gnome.org
[mutter]: https://gitlab.gnome.org/GNOME/mutter
[rectangle]: https://github.com/rxhanson/Rectangle
[sway]: https://github.com/swaywm/sway
[yabai]: https://github.com/koekeishiya/yabai

**Comment by fmlatghor** [comment]
> Could you please post some details about your setup, like the OS you run, your shell and Alacritty version.

I'll add this to the first comment.

> Also, if possible, a screen record would be nice to get a better inside into what the problem looks like. You can simply attach the video to a comment in this issue since GitHub [finally shipped video upload and inline rendering support](https://github.blog/changelog/2021-02-01-expanded-support-for-video-uploads) some weeks ago.

Ok.
 
> I've tried to reproduce the behavior, using `sleep 3 | tput bel` as trigger command, but it works fine in multiple scenarios.
> I use the currently latest Alacritty version `0.7.2` and switched to [multiple color schemes from Alacritty's wiki](https://github.com/alacritty/alacritty/wiki/Color-schemes), but none of them ever hijacked the OS window focus.
> 
>     * With _ZSH_ and _Bash_ on Arch Linux using…
>       
>       * [GNOME](https://www.gnome.org) as desktop environment with the default [Mutter](https://gitlab.gnome.org/GNOME/mutter) rendering engine.
>       * [sway](https://github.com/swaywm/sway) as rendering engine and window manager.
>       * [awesomeWM](https://github.com/awesomeWM/awesome) as window manager.
> 
>     * With _ZSH_ and _Bash_ on macOS using…
>       
>       * the native rendering engine.
>       * [Rectangle](https://github.com/rxhanson/Rectangle) as window manager.
>       * [yabai](https://github.com/koekeishiya/yabai) as window manager.
> 
> 
> To be true, I've no more idea other than referring to search again through the issues in the Alacritty repository and open a new one if it has not been reported yet and if you can reproduce the problem in a stable way.

**Comment by fmlatghor** [comment]
It's not happening anymore. Looks like it was something in my config that was causing it. I will be less quick to open an issue next time.

**Comment by arcticicestudio** [comment]
Nice to see that it works for you now 👍🏼
