### ISSUE TITLE
Nord Aurora theme is not present

### ISSUE THREAD

**Issue by Adyel** [arcticicestudio/nord-alacritty#5]
Hello,
Thanks for this wonderful color scheme. Would you kindly add the Aurora theme for alacritty? 
There is a chance I am not getting this right. Is **Aurora** + **Frost** in the same file?

This is how my terminal looks right now
![image](https://user-images.githubusercontent.com/4653623/80366849-ca1e7400-88ab-11ea-8b33-814ac62445f3.png)

~ Have a good day.

**Comment by arcticicestudio** [comment]
Hi @Adyel :wave:, nice to see you like _Nord_ 😄 

[This repository only provides the actual color codes][s] that _Alacritty_ than uses to colorize the output of commands. This theme provides [all color palettes of _Nord_][c]
Based on your screenshot I guess you're looking for a color theme for the `ls` or respectively `exa` which is [documented on their website in detail][d]. Since `exa` is inspired by and designed as replacement for `ls` you could simply use [Nord dircolors][nd] to get a style that matches _Nord_'s colorization design.

Please let me know if this answers your question or if I misunderstood your actual problem 😄 

[s]: https://github.com/arcticicestudio/nord-alacritty/blob/develop/src/nord.yml#L11-L35
[d]: https://the.exa.website/docs/colour-themes
[c]: https://www.nordtheme.com/docs/colors-and-palettes
[nd]: https://www.nordtheme.com/ports/dircolors

**Comment by Adyel** [comment]
@arcticicestudio  Thank you very much. You did answer my question. I am sorry my question was not well articulated. You can close this now. 😄
